server {
    listen 8001;
    host 127.0.0.1;
    server_name test_server;
    root docs/fusion_web;
    index index.html;
    client_max_body_size 1024;
    error_page 404 /error/404.html;

    location /tours {
        root docs/fusion_web/tours;
        index index.html;
        autoindex on;
        allow_methods GET POST;
        return /abc/index1.html;
        alias docs/fusion_web/tours_alias;
    }

    location /static {
        allow_methods GET;
        index index.html;
    }

    location cgi-bin {
        root ./cgi;
        cgi_path /usr/bin/python3 /bin/bash;
        cgi_ext .py .sh;
        allow_methods GET POST;
    }
}

server {
    listen 8080;
    host 127.0.0.1;
    server_name second_server;
    root www;
    index home.html;
    client_max_body_size 2048;
    error_page 404 /404.html;

    location / {
        root www/public;
        index index.html;
        allow_methods GET;
    }
}